use std::fs;
use std::path::{Path, PathBuf};
use termwiz::cell::AttributeChange;
use termwiz::color::ColorAttribute;
use termwiz::input::{InputEvent, KeyCode, KeyEvent};
use termwiz::surface::{Change, Position};
use termwiz::terminal::Terminal;

use mux::termwiztermtab::TermWizTerminal;

/// Returns `true` when no `forge.lua` exists yet and the wizard should run.
pub fn should_run_onboarding() -> bool {
    // Check FORGE_CONFIG_FILE env override first
    if let Ok(p) = std::env::var("FORGE_CONFIG_FILE") {
        if Path::new(&p).exists() {
            return false;
        }
    }
    // ~/.forge.lua
    let home = &*config::HOME_DIR;
    if home.join(".forge.lua").exists() {
        return false;
    }
    // ~/.config/forge/forge.lua (via xdg)
    let cfg_dir = config::forge_config_dir();
    if cfg_dir.join("forge.lua").exists() {
        return false;
    }
    true
}

/// Locate an existing WezTerm configuration file, if any.
pub fn find_wezterm_config() -> Option<PathBuf> {
    // WEZTERM_CONFIG_FILE env override
    if let Ok(p) = std::env::var("WEZTERM_CONFIG_FILE") {
        let path = PathBuf::from(&p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = &*config::HOME_DIR;
    // ~/.wezterm.lua
    let p = home.join(".wezterm.lua");
    if p.exists() {
        return Some(p);
    }
    // ~/.config/wezterm/wezterm.lua
    let p = home.join(".config").join("wezterm").join("wezterm.lua");
    if p.exists() {
        return Some(p);
    }
    None
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Very simple heuristic: scan lines of a wezterm.lua for `config.KEY = VALUE`
/// patterns and return (key, wezterm_value, forge_default) triples for known
/// keys where Forge ships a different default.
fn detect_overrides(wezterm_path: &Path) -> Vec<(String, String, String)> {
    let forge_defaults: &[(&str, &str)] = &[
        ("color_scheme", "\"Forge Dark\""),
        ("enable_tab_bar", "false"),
        ("scrollback_lines", "50000"),
    ];

    let content = match fs::read_to_string(wezterm_path) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let mut overrides = Vec::new();
    for (key, forge_val) in forge_defaults {
        // Match lines like:  config.color_scheme = "Catppuccin"
        let needle = format!("config.{}", key);
        for line in content.lines() {
            let trimmed = line.trim();
            if let Some(rest) = trimmed.strip_prefix(&needle) {
                let rest = rest.trim();
                if let Some(rest) = rest.strip_prefix('=') {
                    let user_val = rest.trim().to_string();
                    if user_val != *forge_val {
                        overrides.push((key.to_string(), user_val, forge_val.to_string()));
                    }
                }
            }
        }
    }
    overrides
}

/// Helper to resolve a config key value from the user's override choices.
fn resolve_override_full(
    choices: &[(String, String, String, bool)],
    key: &str,
    forge_default: &str,
) -> String {
    // choices: (key, user_val, forge_val, keep_user)
    for (k, user_val, _forge_val, keep_user) in choices {
        if k == key {
            return if *keep_user {
                user_val.clone()
            } else {
                forge_default.to_string()
            };
        }
    }
    forge_default.to_string()
}

/// Write `forge.lua` using the full override choice data.
fn generate_forge_config_full(
    wezterm_config: &Option<PathBuf>,
    project_dir: &str,
    choices: &[(String, String, String, bool)], // (key, user_val, forge_val, keep_user)
) -> PathBuf {
    let cfg_dir = config::forge_config_dir();
    let _ = fs::create_dir_all(&cfg_dir);
    let dest = cfg_dir.join("forge.lua");

    let mut buf = String::new();
    buf.push_str("-- Forge Terminal Configuration\n");
    buf.push_str("-- Generated by Forge onboarding wizard\n\n");
    buf.push_str("local forge = require(\"forge\")\n");
    buf.push_str("local config = forge.config_builder()\n\n");

    // Theme
    buf.push_str("-- Theme\n");
    let color_scheme = resolve_override_full(choices, "color_scheme", "\"Forge Dark\"");
    buf.push_str(&format!("config.color_scheme = {}\n\n", color_scheme));

    // Side Panel
    buf.push_str("-- Side Panel\n");
    buf.push_str("config.enable_side_panel = true\n");
    let enable_tab_bar = resolve_override_full(choices, "enable_tab_bar", "false");
    buf.push_str(&format!("config.enable_tab_bar = {}\n\n", enable_tab_bar));

    // Claude Sessions
    buf.push_str("-- Claude Sessions\n");
    buf.push_str(&format!(
        "config.default_project_dir = \"{}\"\n",
        project_dir.replace('\\', "\\\\").replace('"', "\\\"")
    ));
    buf.push_str("config.claude_command = \"claude\"\n\n");

    // Scrollback
    buf.push_str("-- Scrollback\n");
    let scrollback = resolve_override_full(choices, "scrollback_lines", "50000");
    buf.push_str(&format!("config.scrollback_lines = {}\n\n", scrollback));

    // Import extra lines from wezterm config
    if let Some(wez_path) = wezterm_config {
        if let Ok(content) = fs::read_to_string(wez_path) {
            let known_keys: &[&str] = &[
                "color_scheme",
                "enable_tab_bar",
                "scrollback_lines",
                "enable_side_panel",
                "default_project_dir",
                "claude_command",
            ];
            let mut extras = Vec::new();
            for line in content.lines() {
                let trimmed = line.trim();
                if trimmed.starts_with("config.") {
                    if let Some(rest) = trimmed.strip_prefix("config.") {
                        let key = rest.split('=').next().unwrap_or("").trim();
                        if !known_keys.contains(&key) {
                            extras.push(trimmed.to_string());
                        }
                    }
                }
            }
            if !extras.is_empty() {
                buf.push_str("-- Imported from WezTerm config\n");
                for line in &extras {
                    buf.push_str(line);
                    buf.push('\n');
                }
                buf.push('\n');
            }
        }
    }

    buf.push_str("return config\n");
    let _ = fs::write(&dest, &buf);
    dest
}

// ---------------------------------------------------------------------------
// Main wizard
// ---------------------------------------------------------------------------

/// Run the onboarding wizard. Returns the path to the generated `forge.lua`,
/// or `None` if the user cancelled.
pub fn run_onboarding(mut term: TermWizTerminal) -> anyhow::Result<Option<PathBuf>> {
    term.set_raw_mode()?;

    // -----------------------------------------------------------------------
    // Screen 1: Welcome
    // -----------------------------------------------------------------------
    loop {
        let changes = vec![
            Change::ClearScreen(ColorAttribute::Default),
            Change::CursorPosition {
                x: Position::Absolute(0),
                y: Position::Absolute(0),
            },
            Change::Title("Forge Onboarding".to_string()),
            Change::Text("Welcome to Forge Terminal\r\n".to_string()),
            Change::Text("========================\r\n\r\n".to_string()),
            Change::Text("Forge is a terminal built for Claude Code.\r\n".to_string()),
            Change::Text("Let's set up your configuration.\r\n\r\n".to_string()),
            Change::Text("Press Enter to continue...\r\n".to_string()),
        ];
        term.render(&changes)?;

        match term.poll_input(None)? {
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Enter,
                ..
            })) => break,
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Escape,
                ..
            })) => return Ok(None),
            _ => {}
        }
    }

    // -----------------------------------------------------------------------
    // Screen 2: Config Import
    // -----------------------------------------------------------------------
    let wezterm_config = find_wezterm_config();
    // (key, user_val, forge_val, keep_user)
    let mut override_choices: Vec<(String, String, String, bool)> = Vec::new();

    if let Some(ref wez_path) = wezterm_config {
        let overrides = detect_overrides(wez_path);
        // Build choices — default to using Forge defaults (keep_user = false)
        for (key, user_val, forge_val) in &overrides {
            override_choices.push((
                key.clone(),
                user_val.clone(),
                forge_val.clone(),
                false, // default: use Forge
            ));
        }

        if override_choices.is_empty() {
            // No conflicts, just inform and move on
            loop {
                let changes = vec![
                    Change::ClearScreen(ColorAttribute::Default),
                    Change::CursorPosition {
                        x: Position::Absolute(0),
                        y: Position::Absolute(0),
                    },
                    Change::Text(format!(
                        "Found WezTerm config: {}\r\n",
                        wez_path.display()
                    )),
                    Change::Text("Importing your settings...\r\n\r\n".to_string()),
                    Change::Text(
                        "No conflicting overrides detected.\r\n\r\n".to_string(),
                    ),
                    Change::Text("Press Enter to continue...\r\n".to_string()),
                ];
                term.render(&changes)?;

                match term.poll_input(None)? {
                    Some(InputEvent::Key(KeyEvent {
                        key: KeyCode::Enter,
                        ..
                    })) => break,
                    Some(InputEvent::Key(KeyEvent {
                        key: KeyCode::Escape,
                        ..
                    })) => return Ok(None),
                    _ => {}
                }
            }
        } else {
            // Walk through each override and let user choose
            let mut idx = 0;
            while idx < override_choices.len() {
                let (ref key, ref user_val, ref forge_val, ref keep_user) =
                    override_choices[idx];
                // Which option is selected: false = Forge default (right), true = keep user (left)
                let mut selection = *keep_user;

                loop {
                    let mut changes = vec![
                        Change::ClearScreen(ColorAttribute::Default),
                        Change::CursorPosition {
                            x: Position::Absolute(0),
                            y: Position::Absolute(0),
                        },
                        Change::Text(format!(
                            "Found WezTerm config: {}\r\n",
                            wez_path.display()
                        )),
                        Change::Text("Importing your settings...\r\n\r\n".to_string()),
                        Change::Text(
                            "The following Forge defaults override your settings:\r\n\r\n"
                                .to_string(),
                        ),
                        Change::Text(format!(
                            "  {}: {} (yours: {})\r\n\r\n",
                            key, forge_val, user_val
                        )),
                    ];

                    // Buttons: [Keep yours]  [Use Forge default]
                    changes.push(Change::Text("    ".to_string()));
                    if selection {
                        changes.push(AttributeChange::Reverse(true).into());
                    }
                    changes.push(Change::Text("[Keep yours]".to_string()));
                    if selection {
                        changes.push(AttributeChange::Reverse(false).into());
                    }

                    changes.push(Change::Text("  ".to_string()));

                    if !selection {
                        changes.push(AttributeChange::Reverse(true).into());
                    }
                    changes.push(Change::Text("[Use Forge default]".to_string()));
                    if !selection {
                        changes.push(AttributeChange::Reverse(false).into());
                    }

                    changes.push(Change::Text(format!(
                        "\r\n\r\n  Override {} of {}. Use Left/Right to choose, Enter to confirm.\r\n",
                        idx + 1,
                        override_choices.len()
                    )));

                    term.render(&changes)?;

                    match term.poll_input(None)? {
                        Some(InputEvent::Key(KeyEvent {
                            key: KeyCode::LeftArrow,
                            ..
                        })) => {
                            selection = true;
                        }
                        Some(InputEvent::Key(KeyEvent {
                            key: KeyCode::RightArrow,
                            ..
                        })) => {
                            selection = false;
                        }
                        Some(InputEvent::Key(KeyEvent {
                            key: KeyCode::Enter,
                            ..
                        })) => {
                            override_choices[idx].3 = selection;
                            break;
                        }
                        Some(InputEvent::Key(KeyEvent {
                            key: KeyCode::Escape,
                            ..
                        })) => return Ok(None),
                        _ => {}
                    }
                }
                idx += 1;
            }
        }
    } else {
        // No wezterm config found
        loop {
            let changes = vec![
                Change::ClearScreen(ColorAttribute::Default),
                Change::CursorPosition {
                    x: Position::Absolute(0),
                    y: Position::Absolute(0),
                },
                Change::Text("No existing WezTerm config found.\r\n".to_string()),
                Change::Text("Starting with Forge defaults.\r\n\r\n".to_string()),
                Change::Text("Press Enter to continue...\r\n".to_string()),
            ];
            term.render(&changes)?;

            match term.poll_input(None)? {
                Some(InputEvent::Key(KeyEvent {
                    key: KeyCode::Enter,
                    ..
                })) => break,
                Some(InputEvent::Key(KeyEvent {
                    key: KeyCode::Escape,
                    ..
                })) => return Ok(None),
                _ => {}
            }
        }
    }

    // -----------------------------------------------------------------------
    // Screen 3: Project Directory
    // -----------------------------------------------------------------------
    let mut input_buf = String::from("~/projects");
    let mut error_msg: Option<String> = None;

    let project_dir = loop {
        let mut changes = vec![
            Change::ClearScreen(ColorAttribute::Default),
            Change::CursorPosition {
                x: Position::Absolute(0),
                y: Position::Absolute(0),
            },
            Change::Text(
                "Default project directory for Claude sessions:\r\n\r\n".to_string(),
            ),
            Change::Text(format!("> {}\r\n\r\n", input_buf)),
            Change::Text(
                "Type a path and press Enter (~ expands to home)\r\n".to_string(),
            ),
            Change::Text(
                "Press Enter with no input to use home directory\r\n".to_string(),
            ),
        ];

        if let Some(ref msg) = error_msg {
            changes.push(Change::Text("\r\n".to_string()));
            changes.push(AttributeChange::Foreground(ColorAttribute::PaletteIndex(1)).into());
            changes.push(Change::Text(format!("  {}\r\n", msg)));
            changes.push(
                AttributeChange::Foreground(ColorAttribute::Default).into(),
            );
        }

        term.render(&changes)?;

        match term.poll_input(None)? {
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Enter,
                ..
            })) => {
                let raw = if input_buf.is_empty() {
                    config::HOME_DIR.to_string_lossy().to_string()
                } else {
                    expand_tilde(&input_buf)
                };
                let path = PathBuf::from(&raw);
                if path.is_dir() {
                    break raw;
                } else {
                    error_msg =
                        Some(format!("Directory does not exist: {}", raw));
                }
            }
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Char(c),
                ..
            })) => {
                input_buf.push(c);
                error_msg = None;
            }
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Backspace,
                ..
            })) => {
                input_buf.pop();
                error_msg = None;
            }
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Escape,
                ..
            })) => return Ok(None),
            _ => {}
        }
    };

    // -----------------------------------------------------------------------
    // Generate config
    // -----------------------------------------------------------------------
    let config_path = generate_forge_config_full(
        &wezterm_config,
        &project_dir,
        &override_choices,
    );

    // -----------------------------------------------------------------------
    // Screen 4: Done
    // -----------------------------------------------------------------------
    loop {
        let changes = vec![
            Change::ClearScreen(ColorAttribute::Default),
            Change::CursorPosition {
                x: Position::Absolute(0),
                y: Position::Absolute(0),
            },
            Change::Text("Setup complete!\r\n\r\n".to_string()),
            Change::Text(format!(
                "Config saved to: {}\r\n\r\n",
                config_path.display()
            )),
            Change::Text(
                "Press Enter to start your first Claude session...\r\n".to_string(),
            ),
        ];
        term.render(&changes)?;

        match term.poll_input(None)? {
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Enter,
                ..
            })) => break,
            Some(InputEvent::Key(KeyEvent {
                key: KeyCode::Escape,
                ..
            })) => return Ok(Some(config_path)),
            _ => {}
        }
    }

    Ok(Some(config_path))
}

/// Expand a leading `~` to the user's home directory.
fn expand_tilde(input: &str) -> String {
    if input == "~" {
        config::HOME_DIR.to_string_lossy().to_string()
    } else if let Some(rest) = input.strip_prefix("~/") {
        format!("{}/{}", config::HOME_DIR.to_string_lossy(), rest)
    } else {
        input.to_string()
    }
}
